spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/hsweb_payment?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: root
logging:
  level:
    org.hswebframework.web: DEBUG
    org.hswebframework.web.cache: WARN
    com.hswebframework.payment: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis: DEBUG

hsweb:
  message:
    mails:
      default:
        host: smtp.qq.com
        port: 587
        username: 123456@qq.com
        password:
  server:
    location: http://xxxx.ngork.io/
  pay:
    notify:
      location: http://xxxx.ngork.io/
    merchant:
      enable-two-factor: true # 开启双重验证
      two-factor-email-notify: true # 开启双重验证邮件通知
      two-factor-email-from: 123456@qq.com #发件人
    channel:
      config-type: db #使用数据库中的配置